[package]
name = "rust-bridge"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["staticlib"]

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1

[dependencies]
framehop = { version = "0.16.0", default-features = false, features = ["macho"] }
object = { version = "0.39.1", default-features = false, features = ["std", "read", "macho"] }
tokio = { version = "1.52.1", features = ["rt"] }
uuid = "1.23.1"
wholesym = "0.8.1"
