#!/usr/bin/env bash
# Copyright 2026 The Sismo Authors. All rights reserved.
# Licensed under the MIT License.

# tools/setup_perfetto.sh — bootstrap the vendored Perfetto subtree at
# third_party/src/perfetto/ and gen a per-target build output dir.
#
# Steps:
#   1. Clone google/perfetto if not already present.
#   2. Run Perfetto's install-build-deps to fetch gn, ninja, clang, protoc.
#   3. gn gen the sismo build output dir with our args.
#
# By default targets the host (out/sismo). Pass a target triple via env:
#
#   tools/setup_perfetto.sh                         # host (out/sismo)
#   SISMO_TARGET=x86_64-linux-gnu \
#     tools/setup_perfetto.sh                       # cross (out/sismo_linux_x64)
#   SISMO_TARGET=aarch64-linux-gnu \
#     tools/setup_perfetto.sh                       # (out/sismo_linux_arm64)
#
# Cross-compile uses `zig cc` / `zig c++` / `zig ar` as a hermetic clang
# drop-in (libc, libc++, lld all bundled with Zig). The user must have
# `zig` on $PATH.
#
# After this runs, `tools/build_perfetto.sh [SISMO_TARGET]` will
# incrementally build the targets sismo needs (traced, traced_perf,
# trace_processor_shell, the libperfetto.a static archive).

set -euo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
PERFETTO_DIR="$REPO/third_party/src/perfetto"
PERFETTO_REMOTE="https://github.com/google/perfetto.git"
PERFETTO_PIN="${PERFETTO_PIN:-}"   # leave empty to use cloned HEAD; set to a tag (e.g. v54.0) to pin
SISMO_TARGET="${SISMO_TARGET:-}"

echo "==> Perfetto subtree at $PERFETTO_DIR"

if [[ ! -d "$PERFETTO_DIR/.git" ]]; then
    echo "==> cloning $PERFETTO_REMOTE"
    git clone --depth 200 "$PERFETTO_REMOTE" "$PERFETTO_DIR"
fi

if [[ -n "$PERFETTO_PIN" ]]; then
    echo "==> pinning to $PERFETTO_PIN"
    git -C "$PERFETTO_DIR" fetch --depth 200 origin tag "$PERFETTO_PIN"
    git -C "$PERFETTO_DIR" checkout "$PERFETTO_PIN"
fi
echo "    at $(git -C "$PERFETTO_DIR" describe --always)"

echo "==> running install-build-deps (fetches gn/ninja/clang/protoc into the subtree)"
# Default scope (no flags) installs the toolchain + dev tools needed for
# native builds. We don't pass --android / --ui / --bazel — they're opt-in.
"$PERFETTO_DIR/tools/install-build-deps"

# Detect host OS for the GN target_os arg.
case "$(uname -s)" in
    Darwin) HOST_OS=mac ;;
    Linux)  HOST_OS=linux ;;
    *) echo "unsupported host: $(uname -s)" >&2 ; exit 1 ;;
esac

# Resolve the target. If $SISMO_TARGET is set we cross-compile via
# `zig cc`; otherwise we use the host toolchain Perfetto fetched.
if [[ -z "$SISMO_TARGET" ]]; then
    OUT_NAME="sismo"
    TARGET_OS="$HOST_OS"
    TARGET_CPU=""
    USE_ZIG_CC=0
else
    case "$SISMO_TARGET" in
        x86_64-linux-gnu|x86_64-linux-musl)
            OUT_NAME="sismo_linux_x64"; TARGET_OS="linux"; TARGET_CPU="x64" ;;
        aarch64-linux-gnu|aarch64-linux-musl)
            OUT_NAME="sismo_linux_arm64"; TARGET_OS="linux"; TARGET_CPU="arm64" ;;
        x86_64-windows-gnu)
            OUT_NAME="sismo_windows_x64"; TARGET_OS="win"; TARGET_CPU="x64" ;;
        aarch64-windows-gnu)
            OUT_NAME="sismo_windows_arm64"; TARGET_OS="win"; TARGET_CPU="arm64" ;;
        *) echo "unsupported SISMO_TARGET '$SISMO_TARGET'" >&2 ; exit 1 ;;
    esac
    if ! command -v zig >/dev/null 2>&1; then
        echo "SISMO_TARGET set but \`zig\` not on \$PATH" >&2
        exit 1
    fi
    USE_ZIG_CC=1
fi

OUT_DIR="$PERFETTO_DIR/out/$OUT_NAME"
echo "==> gn gen $OUT_DIR (target_os=$TARGET_OS${TARGET_CPU:+ target_cpu=$TARGET_CPU})"
mkdir -p "$OUT_DIR"

if [[ "$USE_ZIG_CC" == "1" ]]; then
    cat > "$OUT_DIR/args.gn" <<EOF
# Cross-compile $SISMO_TARGET via \`zig cc\` (clang drop-in with bundled
# libc / libc++ / lld). Generated by tools/setup_perfetto.sh.

is_debug = false
is_clang = true
is_system_compiler = true   # collapse host+target toolchain to one cc/cxx
is_hermetic_clang = false   # don't fetch a vendored Linux clang

target_os = "$TARGET_OS"
target_cpu = "$TARGET_CPU"

# Default on Linux is libperfetto.so; sismo links the static archive,
# matching the macOS / Windows defaults.
monolithic_binaries = true

cc = "zig cc"
cxx = "zig c++"
ar = "zig ar"

# Cross flags applied only to the target toolchain. Host tools (protoc
# + plugins) are built for the build machine's native arch — leave
# extra_host_*flags empty so zig cc picks up the native target.
extra_target_cflags = "-target $SISMO_TARGET"
extra_target_cxxflags = "-target $SISMO_TARGET"
extra_target_ldflags = "-target $SISMO_TARGET -fuse-ld=lld"

enable_perfetto_traced_perf = true
enable_perfetto_traced_probes = true
enable_perfetto_trace_processor_sqlite = true
enable_perfetto_trace_processor_json = false
enable_perfetto_ui = false
enable_perfetto_integration_tests = false
enable_perfetto_unittests = false
EOF
else
    cat > "$OUT_DIR/args.gn" <<EOF
# sismo's GN args for Perfetto. Keep this minimal; sismo doesn't need
# the chromium / android / system-perfetto bits.
is_debug = false
is_clang = true
target_os = "$TARGET_OS"

# We need:
#   - traced + ServiceIPCHost (linkable as in-process)
#   - traced_perf (Linux CPU sampler, in-process thread)
#   - traced_probes (Linux ftrace + procfs producer, in-process thread)
#   - trace_processor_shell (validation in tools/e2e_all_sources.sh)
#   - libperfetto.a (data source registration in sismo's bespoke producers)
enable_perfetto_traced_perf = true
enable_perfetto_traced_probes = true
enable_perfetto_trace_processor_sqlite = true
enable_perfetto_trace_processor_json = false
enable_perfetto_ui = false
enable_perfetto_integration_tests = false
enable_perfetto_unittests = false
EOF
fi

# gn gen needs to be invoked with Perfetto's repo as the source root.
( cd "$PERFETTO_DIR" && tools/gn gen "out/$OUT_NAME" )

echo
echo "==> setup complete"
echo "    args.gn:  $OUT_DIR/args.gn"
echo "    next:     SISMO_TARGET='${SISMO_TARGET}' tools/build_perfetto.sh"
