#!/usr/bin/env python3
# Copyright 2026 The Sismo Authors. All rights reserved.
# Licensed under the Apache License, Version 2.0.

import os
import sys

ROOT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT_DIR)

from python.tools.run_zig import run_zig

run_zig(sys.argv[1:])
